# Generates _includes/diffusion-banner.html: a flow-matching banner where
# samples from a Gaussian are transported along straight paths onto a treeline.
#
# Each dot carries its own start (x0, y0) and end (x1, y1) as CSS custom
# properties; a single shared @keyframes rule in _sass/_wood.scss interpolates
# transform between them. Straight-line interpolation is the point: it is the
# rectified-flow / optimal-transport path, x_t = (1-t)x_0 + t x_1.
#
# Run from the repo root after editing:
#   ruby tools/gen_banner.rb > _includes/diffusion-banner.html

SEED     = 20260807
N_DOTS   = 320
WIDTH    = 1200.0
HEIGHT   = 240.0
BASELINE = 208.0

rng = Random.new(SEED)

# --- target shape: a treeline of pines -------------------------------------
# [centre x, base y, half-width, height]
TREES = [
  [170,  BASELINE,  46,  96],
  [350,  BASELINE,  34,  70],
  [600,  BASELINE,  78, 170],
  [850,  BASELINE,  36,  74],
  [1030, BASELINE,  50, 104],
].freeze

# A pine as three stacked triangles plus a trunk.
def tree_polygons(cx, base, half, height)
  polys = []
  3.times do |tier|
    t     = tier / 3.0
    apex  = base - height * (0.55 + 0.45 * t)
    bot   = base - height * (0.42 * t)
    w     = half * (1.0 - 0.30 * t)
    polys << [[cx - w, bot], [cx, apex], [cx + w, bot]]
  end
  tw = [half * 0.10, 3.0].max
  polys << [[cx - tw, base], [cx - tw, base - height * 0.16],
            [cx + tw, base - height * 0.16], [cx + tw, base]]
  polys
end

def inside?(poly, px, py)
  hit = false
  j = poly.length - 1
  poly.each_with_index do |(xi, yi), i|
    xj, yj = poly[j]
    if (yi > py) != (yj > py) && px < (xj - xi) * (py - yi) / (yj - yi).to_f + xi
      hit = !hit
    end
    j = i
  end
  hit
end

POLYS = TREES.flat_map { |t| tree_polygons(*t) }.freeze

def in_shape?(px, py)
  POLYS.any? { |poly| inside?(poly, px, py) }
end

# --- sampling ---------------------------------------------------------------
def gaussian(rng, mean, sd)
  u1 = 1.0 - rng.rand
  u2 = rng.rand
  mean + sd * Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2.0 * Math::PI * u2)
end

targets = []

# A share of the dots settle along the forest floor so the shape is anchored.
floor_n = (N_DOTS * 0.14).round
floor_n.times do
  targets << [rng.rand * WIDTH, BASELINE + rng.rand * 5.0]
end

# The rest are rejection-sampled from inside the pines.
xs = TREES.map { |cx, _, half, _| [cx - half, cx + half] }
min_x = xs.map(&:first).min
max_x = xs.map(&:last).max

while targets.length < N_DOTS
  px = min_x + rng.rand * (max_x - min_x)
  py = BASELINE - rng.rand * 180.0
  targets << [px, py] if in_shape?(px, py)
end

# --- emit -------------------------------------------------------------------
puts <<~HEAD
  <!-- GENERATED by tools/gen_banner.rb — edit that script, not this file.

       Flow matching, the way it is usually first drawn: samples from a
       Gaussian are transported along straight paths onto the target
       distribution, here a treeline. Each dot carries its own endpoints as
       CSS custom properties; _sass/_wood.scss interpolates between them. -->
  <div class="flow-banner" aria-hidden="true">
    <svg viewBox="0 0 #{WIDTH.to_i} #{HEIGHT.to_i}" preserveAspectRatio="xMidYMid meet" role="presentation">
      <g class="flow-dots">
HEAD

targets.each do |x1, y1|
  # x_0 ~ N(centre, sigma): a single blob, the way the demos draw it.
  x0 = gaussian(rng, WIDTH / 2.0, 132.0)
  y0 = gaussian(rng, HEIGHT / 2.0, 34.0)
  r  = (1.15 + rng.rand * 1.15).round(2)
  # A little spread in timing keeps the cloud from moving as one rigid block.
  d  = (rng.rand * 1.4).round(2)
  printf(
    "      <circle class=\"flow-dot\" r=\"%s\" style=\"--x0:%.1fpx;--y0:%.1fpx;--x1:%.1fpx;--y1:%.1fpx;animation-delay:%ss\"/>\n",
    r, x0, y0, x1, y1, d
  )
end

puts <<~TAIL
      </g>
    </svg>
  </div>
TAIL
